# ===== DATASOURCE CONFIGURATION =====
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=Acesso@123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/inventory_db

# ===== HIBERNATE CONFIGURATION =====
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# ===== DEVELOPMENT MODE =====
quarkus.http.port=8080
